import { useRouter } from "next/router";
import Head from "next/head";
import { useEffect, useState, useRef } from "react";
import styles from "../../styles/Play.module.css";
import { countries } from "../../lib/countries";
import { useSelector, useDispatch } from "react-redux";
import { scoreIncrement } from "../../lib/questionSlice";

export default function Home() {
	const choiceRef = useRef();
	const router = useRouter();
	const { id } = router.query;
	const questions = useSelector((state) => state.question.selectedQuestions);
	const score = useSelector((state) => state.question.score);
	const dispatch = useDispatch();
	const currentCountry = questions.find((q) => q.id == id);

	console.log(currentCountry);

	const nextQuestion = (e) => {
		const choice = e.target.value;

		if (parseInt(id) < questions.length) {
			//user choice
			if (choice === currentCountry.answer) {
				console.log(`Correct!`);
				dispatch(scoreIncrement());
			}
			console.log(score);
			router.push(`/play/${parseInt(id) + 1}`);
		} else {
			if (choice === currentCountry.answer) {
				console.log(`Correct!`);
				dispatch(scoreIncrement());
			}
			router.push(`/results`);
		}
	};

	return (
		<div className={styles.body}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<img
				className={styles.flag}
				src={`https://flagcdn.com/${currentCountry.answer}.svg`}
				width={300}
			/>
			<div>
				<div className={styles.choices}>
					<button
						value={currentCountry.choices[0]}
						onClick={(e) => nextQuestion(e)}
						className={styles.choice}>
						{countries[currentCountry.choices[0]]}
					</button>
					<button
						value={currentCountry.choices[1]}
						onClick={(e) => nextQuestion(e)}
						className={styles.choice}>
						{countries[currentCountry.choices[1]]}
					</button>
				</div>
				<div className={styles.choices}>
					<button
						value={currentCountry.choices[2]}
						onClick={(e) => nextQuestion(e)}
						className={styles.choice}>
						{countries[currentCountry.choices[2]]}
					</button>
					<button
						value={currentCountry.choices[3]}
						onClick={(e) => nextQuestion(e)}
						className={styles.choice}>
						{countries[currentCountry.choices[3]]}
					</button>
				</div>
			</div>
		</div>
	);
}
