import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
	const router = useRouter();
  return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.body}>
				<ul className={styles.container}>
					<li className={styles["hover-underline-animation"]} onClick={() => router.push('/play/1')}>PLAY</li>
				</ul>
			</div>
		</>
  )
}
